name: expandable_x
description: A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
version: 1.0.0
author: Steve Gehrman <steve@distantfutu.re>
homepage: https://github.com/sgehrman/flutter-expandable

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.0.0
