name: expandable
description: A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
version: 4.1.4
#author: Alexander Ryzhov <aryzhov07@gmail.com>
homepage: https://github.com/aryzhov/flutter-expandable

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.0.0
